import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import PriceTicker from "@/components/layouts/PriceTicker";
import Footer from "@/components/layouts/Footer";
import { Suspense } from "react";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense
          fallback={
            <div className="h-18 bg-white border-b border-slate-100 animate-pulse"></div>
          }
        >
          <Navbar />
        </Suspense>
        <PriceTicker />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
